// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoMVCCSHARP.Data;

namespace ProjetoMVCCSHARP.Migrations
{
    [DbContext(typeof(ProjetoMVCCSHARPContext))]
    [Migration("20210519191013_Imagem")]
    partial class Imagem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoMVCCSHARP.Models.Noticia", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Conteudo");

                    b.Property<string>("Imagem");

                    b.Property<string>("Resumo");

                    b.Property<string>("Titulo");

                    b.HasKey("ID");

                    b.ToTable("Noticia");
                });
#pragma warning restore 612, 618
        }
    }
}
